export const GET_BLOGS = "GET_BLOGS";

export const SHOW_ERROR = "SHOW_ERROR";

export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const TOKEN_FETCH_START = "TOKEN_FETCH_START";
export const TOKEN_FETCH_SUCCESS = "TOKEN_FETCH_SUCCESS";
export const TOKEN_FETCH_FAIL = "TOKEN_FETCH_FAIL";

export const TOKEN_VALIDATION_START = "TOKEN_VALIDATION_START";
export const TOKEN_VALIDATION_SUCCESS = "TOKEN_VALIDATION_SUCCESS";
export const TOKEN_VALIDATION_FAIL = "TOKEN_VALIDATION_FAIL";