export const GET_BLOGS = "GET_BLOGS";

export const SHOW_ERROR = "SHOW_ERROR";

export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const TOKEN_FETCH_START = "TOKEN_FETCH_START";
export const TOKEN_FETCH_SUCCESS = "TOKEN_FETCH_SUCCESS";
export const TOKEN_FETCH_FAIL = "TOKEN_FETCH_FAIL";

export const TOKEN_ADD_START = "TOKEN_ADD_START";
export const TOKEN_ADD_SUCCESS = "TOKEN_ADD_SUCCESS";
export const TOKEN_ADD_FAIL = "TOKEN_ADD_FAIL";

export const PREDICTION_START = "PREDICTION_START";
export const PREDICTION_SUCCESS = "PREDICTION_SUCCESS";
export const PREDICTION_FAIL = "PREDICTION_FAIL";

export const TOKEN_VALIDATION_START = "TOKEN_VALIDATION_START";
export const TOKEN_VALIDATION_SUCCESS = "TOKEN_VALIDATION_SUCCESS";
export const TOKEN_VALIDATION_FAIL = "TOKEN_VALIDATION_FAIL";

export const MARKET_INFO_FETCH_START = "MARKET_INFO_FETCH_START";
export const MARKET_INFO_FETCH_SUCCESS = "MARKET_INFO_FETCH_SUCCESS";
export const MARKET_INFO_FETCH_FAIL = "MARKET_INFO_FETCH_FAIL";

export const LOGIN_HISTORY_FETCH_START = "LOGIN_HISTORY_FETCH_START";
export const LOGIN_HISTORY_FETCH_SUCCESS = "LOGIN_HISTORY_FETCH_SUCCESS";
export const LOGIN_HISTORY_FETCH_FAIL = "LOGIN_HISTORY_FETCH_FAIL";

export const EXCHANGE_RATE_RETRIEVE_START = "EXCHANGE_RATE_RETRIEVE_START";
export const EXCHANGE_RATE_RETRIEVE_SUCCESS = "EXCHANGE_RATE_RETRIEVE_SUCCESS";
export const EXCHANGE_RATE_RETRIEVE_FAIL = "EXCHANGE_RATE_RETRIEVE_FAIL";

export const COMPONENT_TICK_UPDATE_START = "COMPONENT_TICK_UPDATE_START";
export const COMPONENT_TICK_UPDATE = "COMPONENT_TICK_UPDATE";

export const TICK_UPDATE_START = "TICK_UPDATE_START";
export const TICK_UPDATE_SUCCESS = "TICK_UPDATE_SUCCESS";
export const TICK_HISTORY_SUCCESS = "TICK_HISTORY_SUCCESS";
export const SPARKLINES_TICK_UPDATE_SUCCESS = "SPARKLINES_TICK_UPDATE_SUCCESS";
export const SPARKLINES_TICK_HISTORY_SUCCESS = "SPARKLINES_TICK_HISTORY_SUCCESS";
export const TICK_UPDATE_FAIL = "TICK_UPDATE_FAIL";